<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">
        <div class="d-flex justify-content-center">
          <img src="/img/check.png" />
        </div>

        <div class="row">
          <div class="col text-center">
            <h2>Registro realizado com sucesso!</h2>
          </div>
        </div>

        <div class="row">
          <div class="col text-center">
            <a href="/" class="btn btn-info btn-block">VOLTAR A PÁGINA INICIAL</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>