<style>
    #listarCliente {
        display: none;
    }

    .display-align {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .form-group {
        margin-bottom: 18px;
    }
    @media (max-width: 768px) {
        .form-group {
            width: 100%;
        }
    }
</style>

<h1>Clientes</h1>
<?php if ($this->view->editarCadastro) {?>
    <a href="/cliente"><button type="button" class="btn-cadastrar btn btn-success btn-lg">Cadastrar</button></a>
<?php }?>
<button type="button" class="btn-cadastrar btn btn-info btn-lg"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?></button>
<button type="button" class="btn-listar btn btn-secondary btn-lg">Listar</button>

<div id="cadastrarCliente" style="display: <?=($this->view->erroCadastro || $this->view->editarCadastro ? '' : 'none')?>">
    <hr class="my-4">
    <h3 class="text-center mb-4"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?> cliente</h3>

    <form method="POST" action="/<?=($this->view->editarCadastro ? 'editarCliente' : 'registrarCliente')?>">
        <input hidden type="text" name="id" value="<?=($_GET['id'] ? $_GET['id'] : '')?>">

        <div class="form-group">
            <input id="nome" placeholder="Nome" type="text" class="form-control" name="nome" value="<?=($this->view->cliente['nome'] ? $this->view->cliente['nome'] : '')?>" autocomplete="off">
        </div>

        <div class="row">
            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="email" placeholder="E-mail" type="email" class="form-control" name="email" value="<?=$this->view->cliente['email']?>" autocomplete="off">
                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="telefone" placeholder="Telefone" type="text" id="telefone" class="form-control telefone" name="telefone" value="<?=$this->view->cliente['telefone']?>" autocomplete="off">
                </div>
            </div>
        </div>

        <div class="form-group">
            <input id="endereco" placeholder="Endereço" type="text" class="form-control" name="endereco" value="<?=$this->view->cliente['endereco']?>" autocomplete="off">
        </div>

        <div class="display-align">
            <input type="hidden" name="cadastrarCliente" value="cadastrarCliente" />
            <button id="proximo" type="submit" name="cadastrarCliente" value="1" class="btn btn-success" data-action='submit'><?=($this->view->editarCadastro ? 'Editar' : 'Salvar')?></button>
        </div>

        <?php if ($this->view->erroCadastro) {?>
            <small class="form-text text-danger">*Erro ao tentar cadastrar cliente, verifique os campos corretamente!</small>
        <?php }?>
    </form>
</div>

<div id="listarCliente">
    <hr class="my-4">
    <h3 class="text-center mb-4">Listar clientes</h3>

    <div class="col-lg-12 mb-lg-0 pd-tp-30">
        <form id="lista" method="POST" action="/registrar">
            <div class="table-wrapper">
                <table class="table table-striped table-round-corner">
                    <thead class="header-tabela">
                        <tr>
                            <th>Ações</th>
                            <th></th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Telefone</th>
                            <th>Endereço</th>
                        </tr>
                    </thead>

                    <tbody class="body-tabela">
                        <?php if ($this->view->dados) {
                            foreach($this->view->dados as $ind => $cliente) {?>
                                <tr>
                                    <td><a href="/cliente?ok=editarCliente&id=<?php echo $cliente['id'];?>"><button type="button" class="btn-editar btn btn-primary btn-lg">Editar</button></a></td>
                                    <td><a href="/cliente?ok=excluirCliente&id=<?php echo $cliente['id'];?>"><button type="button" class="btn-excluir btn btn-danger btn-lg">Excluir</button></a></td>
                                    <td><a href="#"><?=$cliente['nome']?></a></td>
                                    <td><a href="#"><?=$cliente['email']?></a></td>
                                    <td><a href="#"><?=$cliente['telefone']?></a></td>
                                    <td><a href="#"><?=$cliente['endereco']?></a></td>
                                </tr>
                            <?php } 
                        } ?>
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

<script>
    $(".btn-cadastrar").on( "click", function() {
        $( "#cadastrarCliente" ).toggle( "slow" );
    });

    $(".btn-listar").on( "click", function() {
        $( "#listarCliente" ).toggle( "slow" );
    });
</script>