<h1>Contato</h1>
<p>Caso tenha alguma dúvida!</p>

<hr>

<div class="row">
    <h4 class="pb-4">Entre em contato</h4>

    <div class="col-lg-6 col-md-12">
        <p><i class="fas fa-phone me-3" aria-hidden="true"></i> <a class="text-reset fw-bold" href="https://web.whatsapp.com/send?phone=5544991416324" title="Entrar em contato" target="_blank">+55 44 99141-6324</a></p>
    </div>

    <div class="col-lg-6 col-md-12">
        <p><i class="fas fa-envelope me-3" aria-hidden="true"></i>stefaniepereirafernandes@email.com</p>
    </div>
</div>
