<style>
    #listarItem {
        display: none;
    }

    .display-align {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .form-group {
        margin-bottom: 18px;
    }
    @media (max-width: 768px) {
        .form-group {
            width: 100%;
        }
    }
</style>

<h1>Itens do Pedidos</h1>
<?php if ($this->view->editarCadastro) {?>
    <a href="/item"><button type="button" class="btn-cadastrar btn btn-success btn-lg">Cadastrar</button></a>
<?php }?>
<button type="button" class="btn-cadastrar btn btn-info btn-lg"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?></button>
<button type="button" class="btn-listar btn btn-secondary btn-lg">Listar</button>

<div id="registrarItem" style="display: <?=($this->view->erroCadastro || $this->view->editarCadastro ? '' : 'none')?>">
    <hr class="my-4">
    <h3 class="text-center mb-4"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?> item</h3>

    <form method="POST" action="/<?=($this->view->editarCadastro ? 'editarItem' : 'registrarItem')?>">
        <input hidden type="text" name="id" value="<?=($_GET['id'] ? $_GET['id'] : '')?>">

        <div class="row">
            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <select id="pedido_fk" name="pedido_fk" class="form-select" aria-label="Pedidos">
                        <option>Selecione o Pedido</option>
                        <?php foreach ($this->view->pedido as $ind => $pedido) {?>
                            <option <?=($this->view->item['pedido_fk'] == $pedido['id'] ? 'selected' : '')?> value="<?=$pedido['id']?>"><?=$pedido['id']?></option>
                        <?php }?>
                    </select>
                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <select id="produto_fk" name="produto_fk" class="form-select" aria-label="Produto">
                        <option>Selecione o Produto</option>
                        <?php foreach ($this->view->produto as $ind => $produto) {?>
                            <option <?=($this->view->item['produto_fk'] == $produto['id'] ? 'selected' : '')?> value="<?=$produto['id']?>"><?=$produto['nome']?></option>
                        <?php }?>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="quantidade" placeholder="Quantidade" type="text" id="quantidade" class="form-control" name="quantidade" value="<?=$this->view->item['quantidade']?>" autocomplete="off">
                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="preco_uni" placeholder="Preço" type="text" id="preco_uni" class="form-control" name="preco_uni" value="<?=$this->view->item['preco_uni']?>" autocomplete="off">
                </div>
            </div>
        </div>

        <div class="display-align">
            <input type="hidden" name="registrarItem" value="registrarItem" />
            <button id="proximo" type="submit" name="registrarItem" value="1" class="btn btn-success" data-action='submit'><?=($this->view->editarCadastro ? 'Editar' : 'Salvar')?></button>
        </div>

        <?php if ($this->view->erroCadastro) {?>
            <small class="form-text text-danger">*Erro ao tentar cadastrar item, verifique os campos corretamente!</small>
        <?php }?>
    </form>
</div>

<div id="listarItem">
    <hr class="my-4">
    <h3 class="text-center mb-4">Listar items</h3>

    <div class="col-lg-12 mb-lg-0 pd-tp-30">
        <form id="lista" method="POST" action="/registrar">
            <div class="table-wrapper">
                <table class="table table-striped table-round-corner">
                    <thead class="header-tabela">
                        <tr>
                            <th>Ações</th>
                            <th></th>
                            <th>Pedidos</th>
                            <th>Produtos</th>
                            <th>Quantidade</th>
                            <th>Preço</th>
                        </tr>
                    </thead>

                    <tbody class="body-tabela">
                        <?php if ($this->view->dados) {
                            foreach($this->view->dados as $ind => $item) {?>
                                <tr>
                                    <td><a href="/item?ok=editarItem&id=<?php echo $item['id'];?>"><button type="button" class="btn-editar btn btn-primary btn-lg">Editar</button></a></td>
                                    <td><a href="/item?ok=excluirItem&id=<?php echo $item['id'];?>"><button type="button" class="btn-excluir btn btn-danger btn-lg">Excluir</button></a></td>
                                    <?php if ($this->view->pedido) {
                                        foreach ($this->view->pedido as $ind2 => $pedido) {
                                            if ($item['pedido_fk'] == $pedido['id']) {?>
                                                <td><a href="/item?ok=editarItem&id=<?php echo $item['id'];?>"><?=$pedido['id']?></a></td>
                                            <?php }
                                        }
                                    }?>
                                    <?php if ($this->view->produto) {
                                        foreach ($this->view->produto as $ind3 => $produto) {
                                            if ($item['produto_fk'] == $produto['id']) {?>
                                                <td><a href="/item?ok=editarItem&id=<?php echo $item['id'];?>"><?=$produto['nome']?></a></td>
                                            <?php }
                                        }
                                    }?>
                                    <td><a href="/item?ok=editarItem&id=<?php echo $item['id'];?>"><?=$item['quantidade']?></a></td>
                                    <td><a href="/item?ok=editarItem&id=<?php echo $item['id'];?>"><?=($item['preco_uni'] ? 'R$ ' . $item['preco_uni'] : '')?></a></td>
                                </tr>
                            <?php } 
                        } ?>
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

<script>
    $(".btn-cadastrar").on( "click", function() {
        $( "#registrarItem" ).toggle( "slow" );
    });

    $(".btn-listar").on( "click", function() {
        $( "#listarItem" ).toggle( "slow" );
    });
</script>