<style>
    #listarPedido {
        display: none;
    }

    .display-align {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .form-group {
        margin-bottom: 18px;
    }
    @media (max-width: 768px) {
        .form-group {
            width: 100%;
        }
    }
</style>

<h1>Pedidos</h1>
<?php if ($this->view->editarCadastro) {?>
    <a href="/pedido"><button type="button" class="btn-cadastrar btn btn-success btn-lg">Cadastrar</button></a>
<?php }?>
<button type="button" class="btn-cadastrar btn btn-info btn-lg"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?></button>
<button type="button" class="btn-listar btn btn-secondary btn-lg">Listar</button>

<div id="cadastrarPedido" style="display: <?=($this->view->erroCadastro || $this->view->editarCadastro ? '' : 'none')?>">
    <hr class="my-4">
    <h3 class="text-center mb-4"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?> pedido</h3>

    <form method="POST" action="/<?=($this->view->editarCadastro ? 'editarPedido' : 'registrarPedido')?>">
        <input hidden type="text" name="id" value="<?=($_GET['id'] ? $_GET['id'] : '')?>">

        <div class="form-group">
            <select id="cliente_fk" name="cliente_fk" class="form-select" aria-label="Clientes">
                <option>Selecione o Cliente</option>
                <?php foreach ($this->view->cliente as $ind => $cliente) {?>
                    <option <?=($this->view->pedido['cliente_fk'] == $cliente['id'] ? 'selected' : '')?> value="<?=$cliente['id']?>"><?=$cliente['nome']?></option>
                <?php }?>
            </select>
        </div>

        <div class="row">
            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="data_pedido" placeholder="Data do Pedido" type="date" class="form-control" name="data_pedido" value="<?=$this->view->pedido['data_pedido']?>" autocomplete="off">
                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="total" placeholder="Total" type="text" id="total" class="form-control" name="total" value="<?=$this->view->pedido['total']?>" autocomplete="off">
                </div>
            </div>
        </div>

        <div class="display-align">
            <input type="hidden" name="cadastrarPedido" value="cadastrarPedido" />
            <button id="proximo" type="submit" name="cadastrarPedido" value="1" class="btn btn-success" data-action='submit'><?=($this->view->editarCadastro ? 'Editar' : 'Salvar')?></button>
        </div>

        <?php if ($this->view->erroCadastro) {?>
            <small class="form-text text-danger">*Erro ao tentar cadastrar pedido, verifique os campos corretamente!</small>
        <?php }?>
    </form>
</div>

<div id="listarPedido">
    <hr class="my-4">
    <h3 class="text-center mb-4">Listar pedidos</h3>

    <div class="col-lg-12 mb-lg-0 pd-tp-30">
        <form id="lista" method="POST" action="/registrar">
            <div class="table-wrapper">
                <table class="table table-striped table-round-corner">
                    <thead class="header-tabela">
                        <tr>
                            <th>Ações</th>
                            <th></th>
                            <th>Cliente</th>
                            <th>Data do Pedido</th>
                            <th>Total</th>
                        </tr>
                    </thead>

                    <tbody class="body-tabela">
                        <?php if ($this->view->dados) {
                            foreach($this->view->dados as $ind => $pedido) {?>
                                <tr>
                                    <td><a href="/pedido?ok=editarPedido&id=<?php echo $pedido['id'];?>"><button type="button" class="btn-editar btn btn-primary btn-lg">Editar</button></a></td>
                                    <td><a href="/pedido?ok=excluirPedido&id=<?php echo $pedido['id'];?>"><button type="button" class="btn-excluir btn btn-danger btn-lg">Excluir</button></a></td>
                                    <?php if ($this->view->cliente) {
                                        foreach ($this->view->cliente as $ind2 => $cliente) {
                                            if ($pedido['cliente_fk'] == $cliente['id']) {?>
                                                <td><a href="/pedido?ok=editarPedido&id=<?php echo $pedido['id'];?>"><?=$cliente['nome']?></a></td>
                                            <?php }
                                        }
                                    }?>
                                    <td><a href="/pedido?ok=editarPedido&id=<?php echo $pedido['id'];?>"><?=$pedido['data_pedido']?></a></td>
                                    <td><a href="/pedido?ok=editarPedido&id=<?php echo $pedido['id'];?>"><?=($pedido['total'] ? 'R$ ' . $pedido['total'] : '')?></a></td>
                                </tr>
                            <?php } 
                        } ?>
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

<script>
    $(".btn-cadastrar").on( "click", function() {
        $( "#cadastrarPedido" ).toggle( "slow" );
    });

    $(".btn-listar").on( "click", function() {
        $( "#listarPedido" ).toggle( "slow" );
    });
</script>