<style>
    #listarProduto {
        display: none;
    }

    .display-align {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .form-group {
        margin-bottom: 18px;
    }
    @media (max-width: 768px) {
        .form-group {
            width: 100%;
        }
    }
</style>

<h1>Produtos</h1>
<?php if ($this->view->editarCadastro) {?>
    <a href="/produto"><button type="button" class="btn-cadastrar btn btn-success btn-lg">Cadastrar</button></a>
<?php }?>
<button type="button" class="btn-cadastrar btn btn-info btn-lg"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?></button>
<button type="button" class="btn-listar btn btn-secondary btn-lg">Listar</button>
<a href="/categoriaProduto"><button type="button" class="btn-listar btn btn-warning btn-lg">Categoria</button></a>

<div id="cadastrarProduto" style="display: <?=($this->view->erroCadastro || $this->view->editarCadastro ? '' : 'none')?>">
    <hr class="my-4">
    <h3 class="text-center mb-4"><?=($this->view->editarCadastro ? 'Editar' : 'Cadastrar')?> produto</h3>

    <form method="POST" action="/<?=($this->view->editarCadastro ? 'editarProduto' : 'registrarProduto')?>">
        <input hidden type="text" name="id" value="<?=($_GET['id'] ? $_GET['id'] : '')?>">

        <div class="row">
            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="nome" placeholder="Nome" type="text" class="form-control" name="nome" value="<?=($this->view->produto['nome'] ? $this->view->produto['nome'] : '')?>" autocomplete="off">
                </div>
            </div>

            <div class="col-lg-6 col-12">
                <div class="form-group">
                    <input id="preco" placeholder="Preço" type="text" id="preco" class="form-control preco" name="preco" value="<?=$this->view->produto['preco']?>" autocomplete="off">
                </div>
            </div>
        </div>

        <div class="form-group">
            <textarea id="descricao" placeholder="Descrição" type="text" class="form-control" name="descricao" rows="5" autocomplete="off"><?=($this->view->produto['descricao'] ? $this->view->produto['descricao'] : '')?></textarea>
        </div>

        <div class="form-group">
            <select id="categoria" name="categoria" class="form-select" aria-label="Categorias">
                <option>Selecione a Categoria</option>
                <?php foreach ($this->view->ctg as $ind => $ctg) {?>
                    <option <?=($this->view->produto['categoria'] == $ctg['id'] ? 'selected' : '')?> value="<?=$ctg['id']?>"><?=$ctg['nome']?></option>
                <?php }?>
            </select>
        </div>

        <div class="display-align">
            <input type="hidden" name="cadastrarProduto" value="cadastrarProduto" />
            <button id="proximo" type="submit" name="cadastrarProduto" value="1" class="btn btn-success" data-action='submit'><?=($this->view->editarCadastro ? 'Editar' : 'Salvar')?></button>
        </div>

        <?php if ($this->view->erroCadastro) {?>
            <small class="form-text text-danger">*Erro ao tentar cadastrar produto, verifique os campos corretamente!</small>
        <?php }?>
    </form>
</div>

<div id="listarProduto">
    <hr class="my-4">
    <h3 class="text-center mb-4">Listar produtos</h3>

    <div class="col-lg-12 mb-lg-0 pd-tp-30">
        <form id="lista" method="POST" action="/registrar">
            <div class="table-wrapper">
                <table class="table table-striped table-round-corner">
                    <thead class="header-tabela">
                        <tr>
                            <th>Ações</th>
                            <th></th>
                            <th>Nome</th>
                            <th>Descrição</th>
                            <th>Preço</th>
                            <th>Categoria</th>
                        </tr>
                    </thead>

                    <tbody class="body-tabela">
                        <?php if ($this->view->dados) {
                            foreach($this->view->dados as $ind => $produto) {?>
                                <tr>
                                    <td><a href="/produto?ok=editarProduto&id=<?php echo $produto['id'];?>"><button type="button" class="btn-editar btn btn-primary btn-lg">Editar</button></a></td>
                                    <td><a href="/produto?ok=excluirProduto&id=<?php echo $produto['id'];?>"><button type="button" class="btn-excluir btn btn-danger btn-lg">Excluir</button></a></td>
                                    <td><a href="/produto?ok=editarProduto&id=<?php echo $produto['id'];?>"><?=$produto['nome']?></a></td>
                                    <td><a href="/produto?ok=editarProduto&id=<?php echo $produto['id'];?>"><?=$produto['descricao']?></a></td>
                                    <td><a href="/produto?ok=editarProduto&id=<?php echo $produto['id'];?>"><?=$produto['preco']?></a></td>
                                    <?php if ($this->view->ctg) {
                                        foreach ($this->view->ctg as $ind2 => $ctg) {
                                            if ($produto['categoria'] == $ctg['id']) {?>
                                                <td><a href="/produto?ok=editarProduto&id=<?php echo $produto['id'];?>"><?=$ctg['nome']?></a></td>
                                            <?php }
                                        }
                                    }?>
                                </tr>
                            <?php } 
                        } ?>
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

<script>
    $(".btn-cadastrar").on( "click", function() {
        $( "#cadastrarProduto" ).toggle( "slow" );
    });

    $(".btn-listar").on( "click", function() {
        $( "#listarProduto" ).toggle( "slow" );
    });
</script>